version: '3'

services:

  test:
    build: .
    restart: never
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bin/wait-for --timeout=300 mariadb-test:3306 redis:6379 -- bundle exec rspec
    depends_on:
      - redis
      - mariadb-test
    environment:
      REDIS_URL: redis://redis/

  processor:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
      - ./example/datasets:/tmp/datasets
    command: bundle exec sidekiq -r ./lib/datasets/sidekiq_jobs.rb
    depends_on:
      - redis
      - mariadb-dev
    environment:
      REDIS_URL: redis://redis/

  sidekiq_web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec puma bin/sidekiq_web.ru
    depends_on:
      - redis
    ports:
      - 9292:9292
    environment:
      REDIS_URL: redis://redis/

  queuer:
    build: .
    restart: never
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
      - ./example/datasets:/tmp/datasets
    command: bin/datasets.rb
    depends_on:
      - redis
      - mariadb-dev
    environment:
      REDIS_URL: redis://redis/

  mariadb-test:
    image: ghcr.io/hathitrust/db-image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: ht
      MYSQL_USER: datasets
      MYSQL_PASSWORD: datasets

  mariadb-dev:
    image: ghcr.io/hathitrust/db-image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: ht
      MYSQL_USER: datasets
      MYSQL_PASSWORD: datasets

  redis:
    image: redis
    restart: always

volumes:
  gem_cache:
