---
x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

x-environment: &environment
  REDIS_URL: redis://redis/
  PREVIEW_EMAIL: true
  MARIADB_HT_RO_HOST: mariadb-dev
  MARIADB_HT_RO_USERNAME: datasets
  MARIADB_HT_RO_PASSWORD: datasets
  MARIADB_HT_RO_DATABASE: ht

x-common-service: &common-service
  build:
    context: .
    target: base
  volumes:
    - .:/usr/src/app
    - gem_cache:/gems
    - ./example/datasets:/tmp/datasets
  environment: *environment

services:

  test:
    <<: *common-service
    restart: never
    command: bundle exec rspec
    depends_on:
      redis: *healthy
      mariadb-test: *healthy
    environment:
      <<: *environment
      MARIADB_HT_RO_HOST: mariadb-test

  processor:
    <<: *common-service
    restart: always
    command: bundle exec sidekiq -r ./lib/datasets/sidekiq_jobs.rb
    depends_on:
      redis: *healthy
      mariadb-dev: *healthy

  sidekiq_web:
    <<: *common-service
    restart: always
    command: bundle exec puma bin/sidekiq_web.ru
    depends_on:
      redis: *healthy
    ports:
      - 9292:9292

  queuer:
    <<: *common-service
    restart: never
    command: bin/datasets.rb
    depends_on:
      redis: *healthy
      mariadb-dev: *healthy

  mariadb-dev: &mariadb
    image: ghcr.io/hathitrust/db-image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: ht
      MYSQL_USER: datasets
      MYSQL_PASSWORD: datasets
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]

  mariadb-test: *mariadb

  redis:
    image: redis
    restart: always
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "redis-cli", "ping"]

volumes:
  gem_cache:
