version: '3'

services:

  test:
    build: .
    restart: never
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bin/wait-for --timeout=300 mariadb-test:3306 redis:6379 -- bundle exec rspec
    depends_on:
      - redis
      - mariadb-test

  worker:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
      - ./example/datasets:/tmp/datasets
    command: bundle exec rake resque:pool
    depends_on:
      - redis
      - mariadb-dev

  queuer:
    build: .
    restart: never
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
      - ./example/datasets:/tmp/datasets
    command: bin/datasets.rb
    depends_on:
      - redis
      - mariadb-dev

  mariadb-test:
    image: hathitrust/db-image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: ht
      MYSQL_USER: datasets
      MYSQL_PASSWORD: datasets

  mariadb-dev:
    image: hathitrust/db-image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: ht
      MYSQL_USER: datasets
      MYSQL_PASSWORD: datasets

  resque-web:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      - redis
    command: bundle exec bin/resque_web.sh

  redis:
    image: redis
    restart: always

volumes:
  gem_cache:
