name: Deploy

on:
    workflow_dispatch:
        inputs:
            branch_hash:
                description: Branch sha or revision to deploy (Defaults to branch sha)
            environments:
                description: The environment to deploy to
                type: choice
                default: testing
                options:
                - testing
                - production

jobs:
    deploy:
      name: Deploy to ${{inputs.environments}}
      uses: hathitrust/github_actions/.github/workflows/deploy.yml@77c502edf6fbbc42378a65373c2f80ff9c5ea4ef #v1.8.0
      with:
        image: ghcr.io/${{ github.repository }}:${{ inputs.branch_hash || github.sha}}
        file: environments/${{ github.event.repository.name }}/${{inputs.environments}}/datasets.txt
        CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
        CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
        CONFIG_REPO_RW_KEY: ${{secrets.CONFIG_REPO_RW_KEY}}
      permissions:
          contents: read
          packages: write
