name: Docker Tag Latest Release

on:
  release:
    types: [ released ]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: github.com/hathitrust/tag-release@v1
        with:
          registry_token: ${{ github.token }}
          existing_tag: ghcr.io/hathitrust/datasets-unstable:${{ github.sha }}
          image: ${{ github.event.inputs.image_to_tag }}
          new_tag: ${{ github.event.inputs.tag }}
