---
name: Docker Tag Latest Release

on:
  release:
    types: [released]

jobs:
  tag-release:
    uses: hathitrust/github_actions/.github/workflows/tag-release.yml@77c502edf6fbbc42378a65373c2f80ff9c5ea4ef #v1.8.0
    with:
      registry_token: ${{ github.token }}
      existing_tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
      image: ghcr.io/${{ github.repository }}
      new_tag: ${{ github.event.release.tag_name }}
